// <auto-generated />
using System;
using BusinessModel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessModel.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20250805120124_AddedCustomerImageUrl")]
    partial class AddedCustomerImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessModel.Models.Auto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VehicleId");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Registered")
                        .HasColumnType("datetime2");

                    b.Property<int>("TopSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96ba173e-04ae-3bcd-9986-9e56f0adbf3a"),
                            Color = 50,
                            Fuel = "Gasoline",
                            Manufacturer = "Kia",
                            Model = "Taurus",
                            Registered = new DateTime(1992, 11, 19, 5, 40, 6, 742, DateTimeKind.Unspecified).AddTicks(682),
                            TopSpeed = 180,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = new Guid("098b6ecc-5714-b09a-36cf-d6280bb3c707"),
                            Color = 35,
                            Fuel = "Diesel",
                            Manufacturer = "Porsche",
                            Model = "A4",
                            Registered = new DateTime(2015, 1, 5, 20, 13, 4, 66, DateTimeKind.Unspecified).AddTicks(4443),
                            TopSpeed = 100,
                            Type = "Extended Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("6b676e09-f1e7-460d-d827-baed2722fbb9"),
                            Color = 96,
                            Fuel = "Gasoline",
                            Manufacturer = "Ford",
                            Model = "Colorado",
                            Registered = new DateTime(1990, 5, 21, 15, 32, 52, 850, DateTimeKind.Unspecified).AddTicks(9627),
                            TopSpeed = 110,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = new Guid("afa886b3-7672-a763-8137-69819aadebb3"),
                            Color = 106,
                            Fuel = "Electric",
                            Manufacturer = "Audi",
                            Model = "Escalade",
                            Registered = new DateTime(2002, 10, 28, 8, 52, 32, 934, DateTimeKind.Unspecified).AddTicks(3650),
                            TopSpeed = 260,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = new Guid("f5e0e49f-710e-2d05-7eef-e9b3e53e429b"),
                            Color = 127,
                            Fuel = "Hybrid",
                            Manufacturer = "Chevrolet",
                            Model = "Camry",
                            Registered = new DateTime(2012, 11, 17, 7, 53, 54, 639, DateTimeKind.Unspecified).AddTicks(1035),
                            TopSpeed = 260,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = new Guid("4af80b60-3e17-1dfd-8462-c009ca918154"),
                            Color = 150,
                            Fuel = "Electric",
                            Manufacturer = "BMW",
                            Model = "F-150",
                            Registered = new DateTime(1990, 4, 16, 16, 27, 45, 17, DateTimeKind.Unspecified).AddTicks(2554),
                            TopSpeed = 250,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("8e7c7406-87b9-1880-10e0-4480ea1527ee"),
                            Color = 71,
                            Fuel = "Hybrid",
                            Manufacturer = "Volvo",
                            Model = "Jetta",
                            Registered = new DateTime(2007, 12, 3, 2, 59, 56, 923, DateTimeKind.Unspecified).AddTicks(9807),
                            TopSpeed = 130,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = new Guid("204e0977-bd4b-d4ab-0dae-11f2d59ab044"),
                            Color = 87,
                            Fuel = "Electric",
                            Manufacturer = "Cadillac",
                            Model = "Fortwo",
                            Registered = new DateTime(1993, 12, 31, 9, 55, 26, 940, DateTimeKind.Unspecified).AddTicks(2492),
                            TopSpeed = 220,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = new Guid("8c0d3f96-691b-4cc0-a8e0-3f05846b6734"),
                            Color = 122,
                            Fuel = "Diesel",
                            Manufacturer = "Mercedes Benz",
                            Model = "Cruze",
                            Registered = new DateTime(1992, 8, 14, 12, 50, 59, 129, DateTimeKind.Unspecified).AddTicks(8378),
                            TopSpeed = 270,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("3c3e5451-603c-7507-0cf1-f8b7e03d3190"),
                            Color = 106,
                            Fuel = "Gasoline",
                            Manufacturer = "Porsche",
                            Model = "ATS",
                            Registered = new DateTime(2015, 3, 28, 14, 30, 27, 971, DateTimeKind.Unspecified).AddTicks(8568),
                            TopSpeed = 140,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = new Guid("cf2dd82b-4aef-501c-3fbe-1dbc37dc2c83"),
                            Color = 166,
                            Fuel = "Electric",
                            Manufacturer = "Volvo",
                            Model = "ATS",
                            Registered = new DateTime(2008, 12, 23, 14, 12, 3, 887, DateTimeKind.Unspecified).AddTicks(8026),
                            TopSpeed = 130,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("d528f786-e8a1-6f70-0fba-c013640f9118"),
                            Color = 139,
                            Fuel = "Electric",
                            Manufacturer = "Mercedes Benz",
                            Model = "Civic",
                            Registered = new DateTime(1990, 12, 27, 18, 44, 33, 5, DateTimeKind.Unspecified).AddTicks(2070),
                            TopSpeed = 290,
                            Type = "Wagon"
                        },
                        new
                        {
                            Id = new Guid("c93eb3fa-c775-64a7-809f-23a7d7c6757a"),
                            Color = 79,
                            Fuel = "Diesel",
                            Manufacturer = "Ferrari",
                            Model = "XC90",
                            Registered = new DateTime(1994, 12, 22, 17, 42, 1, 582, DateTimeKind.Unspecified).AddTicks(609),
                            TopSpeed = 220,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("885a74c8-413f-d273-bbc3-762e21631ffa"),
                            Color = 172,
                            Fuel = "Electric",
                            Manufacturer = "Lamborghini",
                            Model = "Roadster",
                            Registered = new DateTime(2012, 4, 18, 3, 37, 36, 190, DateTimeKind.Unspecified).AddTicks(8261),
                            TopSpeed = 230,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = new Guid("75b652ba-ea39-b4aa-7f82-ea75551b3e68"),
                            Color = 73,
                            Fuel = "Hybrid",
                            Manufacturer = "Land Rover",
                            Model = "Charger",
                            Registered = new DateTime(2005, 6, 30, 18, 51, 54, 584, DateTimeKind.Unspecified).AddTicks(9082),
                            TopSpeed = 190,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = new Guid("d4481753-a5a5-37aa-5587-0c9f3688cb39"),
                            Color = 164,
                            Fuel = "Hybrid",
                            Manufacturer = "Fiat",
                            Model = "Mustang",
                            Registered = new DateTime(2008, 3, 18, 15, 8, 56, 309, DateTimeKind.Unspecified).AddTicks(7698),
                            TopSpeed = 230,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = new Guid("006adfca-3234-d9a6-8458-ba625ef11604"),
                            Color = 41,
                            Fuel = "Diesel",
                            Manufacturer = "Ferrari",
                            Model = "Roadster",
                            Registered = new DateTime(2006, 12, 22, 5, 3, 0, 422, DateTimeKind.Unspecified).AddTicks(2981),
                            TopSpeed = 230,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = new Guid("d356df07-56e4-6ad4-eb1c-297df43ba576"),
                            Color = 147,
                            Fuel = "Gasoline",
                            Manufacturer = "Toyota",
                            Model = "Countach",
                            Registered = new DateTime(2016, 1, 19, 12, 18, 45, 203, DateTimeKind.Unspecified).AddTicks(7344),
                            TopSpeed = 300,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = new Guid("0cd2476d-22ff-a160-fe82-636220dd5ec1"),
                            Color = 109,
                            Fuel = "Hybrid",
                            Manufacturer = "Bugatti",
                            Model = "Aventador",
                            Registered = new DateTime(2011, 1, 6, 16, 53, 52, 237, DateTimeKind.Unspecified).AddTicks(3211),
                            TopSpeed = 100,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = new Guid("5d6ac921-e645-bf40-348b-b9e98b124ad4"),
                            Color = 170,
                            Fuel = "Hybrid",
                            Manufacturer = "Audi",
                            Model = "Silverado",
                            Registered = new DateTime(2000, 2, 1, 20, 59, 19, 231, DateTimeKind.Unspecified).AddTicks(7590),
                            TopSpeed = 280,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("eca79984-d82c-ac58-df38-d4b04395c41b"),
                            Color = 48,
                            Fuel = "Electric",
                            Manufacturer = "Polestar",
                            Model = "Challenger",
                            Registered = new DateTime(1993, 8, 19, 18, 41, 29, 75, DateTimeKind.Unspecified).AddTicks(9692),
                            TopSpeed = 170,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = new Guid("db37afd2-43a6-09cb-7790-efe5c49df914"),
                            Color = 138,
                            Fuel = "Hybrid",
                            Manufacturer = "Lamborghini",
                            Model = "F-150",
                            Registered = new DateTime(2009, 4, 23, 8, 28, 13, 407, DateTimeKind.Unspecified).AddTicks(2577),
                            TopSpeed = 180,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = new Guid("6f833e07-6cbf-6139-021d-a5d53df4fdb1"),
                            Color = 76,
                            Fuel = "Electric",
                            Manufacturer = "Bugatti",
                            Model = "Land Cruiser",
                            Registered = new DateTime(2011, 3, 1, 19, 44, 4, 533, DateTimeKind.Unspecified).AddTicks(1711),
                            TopSpeed = 210,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = new Guid("aac27e00-53dc-8df7-431a-4d309c23d30c"),
                            Color = 34,
                            Fuel = "Hybrid",
                            Manufacturer = "Bugatti",
                            Model = "Model 3",
                            Registered = new DateTime(2008, 1, 13, 16, 31, 21, 236, DateTimeKind.Unspecified).AddTicks(9236),
                            TopSpeed = 280,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = new Guid("2ae91fbb-c575-5b81-41b4-8f83f1fcc25d"),
                            Color = 100,
                            Fuel = "Gasoline",
                            Manufacturer = "Kia",
                            Model = "Altima",
                            Registered = new DateTime(2006, 3, 19, 5, 27, 3, 405, DateTimeKind.Unspecified).AddTicks(9827),
                            TopSpeed = 170,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("08958e61-1d92-66f1-e6e1-b6068af32981"),
                            Color = 56,
                            Fuel = "Hybrid",
                            Manufacturer = "Toyota",
                            Model = "Prius",
                            Registered = new DateTime(2018, 4, 10, 19, 10, 5, 769, DateTimeKind.Unspecified).AddTicks(1329),
                            TopSpeed = 280,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = new Guid("e1da0fe2-e120-bd38-0ccc-5b889be0bcef"),
                            Color = 33,
                            Fuel = "Electric",
                            Manufacturer = "Ford",
                            Model = "Camaro",
                            Registered = new DateTime(1991, 6, 18, 10, 31, 50, 263, DateTimeKind.Unspecified).AddTicks(4711),
                            TopSpeed = 290,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = new Guid("8ae56a38-9ec7-e2fc-4853-efb3f9b73cd1"),
                            Color = 148,
                            Fuel = "Electric",
                            Manufacturer = "Fiat",
                            Model = "911",
                            Registered = new DateTime(1990, 3, 17, 9, 40, 0, 377, DateTimeKind.Unspecified).AddTicks(2197),
                            TopSpeed = 130,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = new Guid("d30ba08d-bd81-642e-fda7-19a2773a5671"),
                            Color = 44,
                            Fuel = "Gasoline",
                            Manufacturer = "Kia",
                            Model = "Fortwo",
                            Registered = new DateTime(2009, 10, 20, 23, 54, 44, 776, DateTimeKind.Unspecified).AddTicks(5),
                            TopSpeed = 140,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = new Guid("7d0037c3-fac8-907e-bb09-ff57e9bccb7a"),
                            Color = 146,
                            Fuel = "Diesel",
                            Manufacturer = "Bentley",
                            Model = "LeBaron",
                            Registered = new DateTime(2019, 2, 10, 9, 58, 1, 649, DateTimeKind.Unspecified).AddTicks(6898),
                            TopSpeed = 280,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = new Guid("3c2e96c4-9a05-1c50-36e1-72479b804065"),
                            Color = 91,
                            Fuel = "Electric",
                            Manufacturer = "BMW",
                            Model = "Jetta",
                            Registered = new DateTime(1993, 7, 13, 10, 26, 24, 211, DateTimeKind.Unspecified).AddTicks(4072),
                            TopSpeed = 100,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = new Guid("9553b46c-f8c4-bb45-21e3-223be699bd78"),
                            Color = 32,
                            Fuel = "Diesel",
                            Manufacturer = "Cadillac",
                            Model = "Challenger",
                            Registered = new DateTime(1992, 12, 11, 1, 38, 14, 405, DateTimeKind.Unspecified).AddTicks(1666),
                            TopSpeed = 270,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("b4e5f92f-7184-82f5-7b4c-b3c188b2058b"),
                            Color = 62,
                            Fuel = "Diesel",
                            Manufacturer = "Polestar",
                            Model = "Altima",
                            Registered = new DateTime(2015, 1, 13, 0, 34, 26, 78, DateTimeKind.Unspecified).AddTicks(6355),
                            TopSpeed = 290,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = new Guid("06accc59-f220-b0ab-6df5-3f239bdf43c0"),
                            Color = 126,
                            Fuel = "Hybrid",
                            Manufacturer = "Mini",
                            Model = "ATS",
                            Registered = new DateTime(2013, 12, 31, 1, 25, 22, 756, DateTimeKind.Unspecified).AddTicks(5655),
                            TopSpeed = 190,
                            Type = "Extended Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("dff1c635-d6c9-254f-11b6-b48be8d86ad4"),
                            Color = 89,
                            Fuel = "Gasoline",
                            Manufacturer = "Dodge",
                            Model = "Malibu",
                            Registered = new DateTime(2002, 5, 5, 22, 41, 4, 337, DateTimeKind.Unspecified).AddTicks(7342),
                            TopSpeed = 160,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("31e0ac69-24dd-d202-5526-f477402f12e2"),
                            Color = 130,
                            Fuel = "Hybrid",
                            Manufacturer = "Mini",
                            Model = "Cruze",
                            Registered = new DateTime(1992, 11, 25, 4, 53, 21, 573, DateTimeKind.Unspecified).AddTicks(2147),
                            TopSpeed = 210,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("57dfe75b-d6d1-ec53-0beb-388733e9a472"),
                            Color = 48,
                            Fuel = "Gasoline",
                            Manufacturer = "Volvo",
                            Model = "Accord",
                            Registered = new DateTime(2009, 3, 25, 14, 30, 37, 354, DateTimeKind.Unspecified).AddTicks(4653),
                            TopSpeed = 240,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = new Guid("ee7da52a-28c2-1bfc-2082-58844afdcd31"),
                            Color = 118,
                            Fuel = "Hybrid",
                            Manufacturer = "Nissan",
                            Model = "Ranchero",
                            Registered = new DateTime(2005, 2, 15, 23, 28, 55, 656, DateTimeKind.Unspecified).AddTicks(2591),
                            TopSpeed = 150,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = new Guid("ac34f8de-1fce-8789-ef67-85b4b153e890"),
                            Color = 96,
                            Fuel = "Gasoline",
                            Manufacturer = "Mazda",
                            Model = "Fiesta",
                            Registered = new DateTime(2011, 6, 18, 21, 26, 47, 41, DateTimeKind.Unspecified).AddTicks(4098),
                            TopSpeed = 110,
                            Type = "Extended Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("dd33745a-5de8-0b29-d622-fe9ff58d7c2d"),
                            Color = 72,
                            Fuel = "Gasoline",
                            Manufacturer = "Bentley",
                            Model = "F-150",
                            Registered = new DateTime(2020, 1, 29, 12, 16, 47, 908, DateTimeKind.Unspecified).AddTicks(116),
                            TopSpeed = 260,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = new Guid("7113de1b-d977-f0ba-a203-93da379b42a1"),
                            Color = 71,
                            Fuel = "Electric",
                            Manufacturer = "Kia",
                            Model = "Wrangler",
                            Registered = new DateTime(1993, 12, 30, 10, 38, 16, 854, DateTimeKind.Unspecified).AddTicks(8968),
                            TopSpeed = 110,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("e14702f2-80d4-7209-4696-2b17ffd4ebb2"),
                            Color = 127,
                            Fuel = "Hybrid",
                            Manufacturer = "Fiat",
                            Model = "Grand Cherokee",
                            Registered = new DateTime(2015, 1, 11, 17, 33, 23, 139, DateTimeKind.Unspecified).AddTicks(469),
                            TopSpeed = 250,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = new Guid("f5ba9244-a3d2-14c1-b668-2a206e2ff8e6"),
                            Color = 114,
                            Fuel = "Diesel",
                            Manufacturer = "Lamborghini",
                            Model = "XC90",
                            Registered = new DateTime(2016, 2, 23, 7, 24, 46, 336, DateTimeKind.Unspecified).AddTicks(2541),
                            TopSpeed = 210,
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = new Guid("123dcc42-932a-575f-1891-4e024f1a8b37"),
                            Color = 49,
                            Fuel = "Electric",
                            Manufacturer = "Mazda",
                            Model = "2",
                            Registered = new DateTime(2011, 10, 20, 15, 25, 53, 699, DateTimeKind.Unspecified).AddTicks(1825),
                            TopSpeed = 290,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = new Guid("3538837d-c2c3-140b-7037-0e7728949097"),
                            Color = 157,
                            Fuel = "Gasoline",
                            Manufacturer = "Smart",
                            Model = "Camry",
                            Registered = new DateTime(2014, 11, 8, 22, 32, 18, 554, DateTimeKind.Unspecified).AddTicks(7882),
                            TopSpeed = 280,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = new Guid("61e4cca9-c8c0-98c1-d46d-18c08ff15e9c"),
                            Color = 151,
                            Fuel = "Gasoline",
                            Manufacturer = "Jaguar",
                            Model = "Malibu",
                            Registered = new DateTime(1996, 5, 2, 9, 5, 11, 822, DateTimeKind.Unspecified).AddTicks(9467),
                            TopSpeed = 140,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = new Guid("ed3fa262-1c00-c39d-255d-568f68de614a"),
                            Color = 113,
                            Fuel = "Gasoline",
                            Manufacturer = "Maserati",
                            Model = "CTS",
                            Registered = new DateTime(2021, 9, 14, 9, 8, 25, 907, DateTimeKind.Unspecified).AddTicks(278),
                            TopSpeed = 170,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = new Guid("bb21a500-047c-4112-6168-2882be81dac1"),
                            Color = 103,
                            Fuel = "Electric",
                            Manufacturer = "Ferrari",
                            Model = "Ranchero",
                            Registered = new DateTime(2021, 10, 29, 11, 56, 4, 199, DateTimeKind.Unspecified).AddTicks(7300),
                            TopSpeed = 160,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = new Guid("c233bdf6-3030-072b-9951-ce3e47de6120"),
                            Color = 158,
                            Fuel = "Gasoline",
                            Manufacturer = "BMW",
                            Model = "Model S",
                            Registered = new DateTime(2004, 5, 30, 15, 50, 6, 404, DateTimeKind.Unspecified).AddTicks(6007),
                            TopSpeed = 140,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = new Guid("ed71c8a2-0224-1e5f-70c7-432bfe4941e2"),
                            Color = 36,
                            Fuel = "Diesel",
                            Manufacturer = "Mini",
                            Model = "Taurus",
                            Registered = new DateTime(1993, 9, 24, 9, 59, 14, 299, DateTimeKind.Unspecified).AddTicks(8690),
                            TopSpeed = 190,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = new Guid("1619e292-deeb-4447-3ab6-6090fabe4307"),
                            Color = 142,
                            Fuel = "Diesel",
                            Manufacturer = "Volkswagen",
                            Model = "Sentra",
                            Registered = new DateTime(1990, 4, 7, 18, 14, 20, 114, DateTimeKind.Unspecified).AddTicks(6169),
                            TopSpeed = 180,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = new Guid("317dd763-be0b-b0c6-2cb2-85df0a0aec73"),
                            Color = 44,
                            Fuel = "Diesel",
                            Manufacturer = "Kia",
                            Model = "LeBaron",
                            Registered = new DateTime(2015, 9, 30, 10, 55, 30, 836, DateTimeKind.Unspecified).AddTicks(4947),
                            TopSpeed = 240,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("2ecd2447-545c-91fc-cb8f-2fb63e6dad3b"),
                            Color = 150,
                            Fuel = "Hybrid",
                            Manufacturer = "Dodge",
                            Model = "Element",
                            Registered = new DateTime(1991, 9, 12, 0, 29, 25, 445, DateTimeKind.Unspecified).AddTicks(5446),
                            TopSpeed = 180,
                            Type = "Extended Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("c618fc38-34f3-faf5-3dc6-1e360d3d8f69"),
                            Color = 137,
                            Fuel = "Hybrid",
                            Manufacturer = "Ferrari",
                            Model = "Taurus",
                            Registered = new DateTime(2010, 9, 29, 13, 47, 50, 292, DateTimeKind.Unspecified).AddTicks(1860),
                            TopSpeed = 260,
                            Type = "Extended Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("ed9206ad-94fc-6870-dad2-459531438d08"),
                            Color = 62,
                            Fuel = "Hybrid",
                            Manufacturer = "Chrysler",
                            Model = "Land Cruiser",
                            Registered = new DateTime(1993, 2, 3, 23, 17, 4, 785, DateTimeKind.Unspecified).AddTicks(8840),
                            TopSpeed = 220,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = new Guid("0af6fda0-05a9-bbbd-8f5c-a96bc06147f9"),
                            Color = 50,
                            Fuel = "Diesel",
                            Manufacturer = "Fiat",
                            Model = "Expedition",
                            Registered = new DateTime(2012, 3, 17, 6, 18, 8, 119, DateTimeKind.Unspecified).AddTicks(5964),
                            TopSpeed = 110,
                            Type = "Wagon"
                        },
                        new
                        {
                            Id = new Guid("26ce265d-e3c3-e9bb-638d-cff1ef0589c7"),
                            Color = 147,
                            Fuel = "Hybrid",
                            Manufacturer = "Chevrolet",
                            Model = "Alpine",
                            Registered = new DateTime(2021, 7, 27, 9, 50, 17, 365, DateTimeKind.Unspecified).AddTicks(5050),
                            TopSpeed = 240,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("dd16a7cd-242e-dc92-d3d8-5598e4dadffa"),
                            Color = 161,
                            Fuel = "Diesel",
                            Manufacturer = "Volkswagen",
                            Model = "Fortwo",
                            Registered = new DateTime(2017, 11, 9, 5, 17, 15, 910, DateTimeKind.Unspecified).AddTicks(3560),
                            TopSpeed = 150,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = new Guid("06dcf357-27fb-124c-6fd4-4e017ead058d"),
                            Color = 78,
                            Fuel = "Electric",
                            Manufacturer = "Audi",
                            Model = "Durango",
                            Registered = new DateTime(2013, 2, 12, 23, 58, 49, 837, DateTimeKind.Unspecified).AddTicks(1136),
                            TopSpeed = 300,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = new Guid("2182eca5-e13f-42c6-f9dc-37bee9511e96"),
                            Color = 113,
                            Fuel = "Electric",
                            Manufacturer = "Chrysler",
                            Model = "Malibu",
                            Registered = new DateTime(2003, 11, 29, 11, 0, 26, 744, DateTimeKind.Unspecified).AddTicks(27),
                            TopSpeed = 270,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = new Guid("46d24d60-75ad-f42d-55bd-86371979060d"),
                            Color = 120,
                            Fuel = "Hybrid",
                            Manufacturer = "Jaguar",
                            Model = "CX-9",
                            Registered = new DateTime(2009, 5, 18, 20, 38, 5, 243, DateTimeKind.Unspecified).AddTicks(8184),
                            TopSpeed = 210,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = new Guid("39a63b1b-76fc-b554-a80f-1321d36c9b18"),
                            Color = 40,
                            Fuel = "Electric",
                            Manufacturer = "Audi",
                            Model = "Model 3",
                            Registered = new DateTime(1998, 11, 3, 18, 44, 33, 135, DateTimeKind.Unspecified).AddTicks(796),
                            TopSpeed = 160,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = new Guid("78ae1d05-3b95-4031-b419-5fb60b073b30"),
                            Color = 84,
                            Fuel = "Hybrid",
                            Manufacturer = "Honda",
                            Model = "Land Cruiser",
                            Registered = new DateTime(1992, 8, 7, 4, 1, 40, 855, DateTimeKind.Unspecified).AddTicks(7730),
                            TopSpeed = 150,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = new Guid("9195a032-88c5-663c-edb8-21a01c4efdbf"),
                            Color = 165,
                            Fuel = "Diesel",
                            Manufacturer = "Porsche",
                            Model = "ATS",
                            Registered = new DateTime(1997, 2, 16, 21, 29, 14, 402, DateTimeKind.Unspecified).AddTicks(7108),
                            TopSpeed = 100,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = new Guid("9c911090-df69-85f9-f3fe-c57bd8ffa96c"),
                            Color = 129,
                            Fuel = "Hybrid",
                            Manufacturer = "Jaguar",
                            Model = "El Camino",
                            Registered = new DateTime(2005, 4, 16, 20, 34, 31, 596, DateTimeKind.Unspecified).AddTicks(6569),
                            TopSpeed = 140,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = new Guid("4280e11f-668e-a858-50bd-ea058034ecd2"),
                            Color = 31,
                            Fuel = "Electric",
                            Manufacturer = "Kia",
                            Model = "Expedition",
                            Registered = new DateTime(2019, 10, 17, 9, 57, 21, 230, DateTimeKind.Unspecified).AddTicks(2348),
                            TopSpeed = 300,
                            Type = "Extended Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("0bd0bf25-e516-0354-b8a6-aa71bae89d6a"),
                            Color = 171,
                            Fuel = "Diesel",
                            Manufacturer = "Jeep",
                            Model = "2",
                            Registered = new DateTime(2007, 12, 19, 21, 28, 15, 242, DateTimeKind.Unspecified).AddTicks(2188),
                            TopSpeed = 210,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = new Guid("a5cc3829-7d2c-bbca-c4c8-0e5b83be5b41"),
                            Color = 48,
                            Fuel = "Electric",
                            Manufacturer = "Chrysler",
                            Model = "Model T",
                            Registered = new DateTime(2013, 2, 3, 5, 48, 50, 296, DateTimeKind.Unspecified).AddTicks(7020),
                            TopSpeed = 100,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = new Guid("89e9ea31-9314-e14b-1437-c4a7d24a4028"),
                            Color = 52,
                            Fuel = "Diesel",
                            Manufacturer = "Jeep",
                            Model = "Impala",
                            Registered = new DateTime(2016, 7, 20, 7, 20, 19, 569, DateTimeKind.Unspecified).AddTicks(1634),
                            TopSpeed = 260,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = new Guid("59c2ac19-7a94-bb04-9b52-759bbb43f4b5"),
                            Color = 153,
                            Fuel = "Diesel",
                            Manufacturer = "Porsche",
                            Model = "Silverado",
                            Registered = new DateTime(1994, 6, 25, 1, 45, 36, 699, DateTimeKind.Unspecified).AddTicks(3278),
                            TopSpeed = 220,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("d281f688-4534-f073-1985-5dcfdc5239b6"),
                            Color = 73,
                            Fuel = "Diesel",
                            Manufacturer = "Nissan",
                            Model = "1",
                            Registered = new DateTime(1995, 1, 17, 6, 26, 41, 776, DateTimeKind.Unspecified).AddTicks(1547),
                            TopSpeed = 130,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = new Guid("3791e585-6cc3-b1c1-685a-953a6212a7cf"),
                            Color = 109,
                            Fuel = "Gasoline",
                            Manufacturer = "Mercedes Benz",
                            Model = "Roadster",
                            Registered = new DateTime(2010, 11, 3, 2, 18, 6, 879, DateTimeKind.Unspecified).AddTicks(4971),
                            TopSpeed = 110,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = new Guid("c2ed6317-ea7f-95a9-c22b-47fceda30db0"),
                            Color = 45,
                            Fuel = "Diesel",
                            Manufacturer = "Honda",
                            Model = "CX-9",
                            Registered = new DateTime(1990, 7, 27, 10, 31, 46, 628, DateTimeKind.Unspecified).AddTicks(854),
                            TopSpeed = 240,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = new Guid("40c0a3d7-0104-01f1-9927-7179d3d5aa42"),
                            Color = 141,
                            Fuel = "Gasoline",
                            Manufacturer = "Maserati",
                            Model = "Volt",
                            Registered = new DateTime(2013, 12, 14, 19, 31, 30, 210, DateTimeKind.Unspecified).AddTicks(9295),
                            TopSpeed = 210,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = new Guid("76682cb9-03df-6842-fed0-4b161ebeaaa4"),
                            Color = 61,
                            Fuel = "Hybrid",
                            Manufacturer = "Ferrari",
                            Model = "Grand Cherokee",
                            Registered = new DateTime(1999, 11, 1, 5, 7, 46, 873, DateTimeKind.Unspecified).AddTicks(5307),
                            TopSpeed = 130,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = new Guid("15d9db3a-360b-74af-09bc-8d06139b8a12"),
                            Color = 143,
                            Fuel = "Gasoline",
                            Manufacturer = "Chevrolet",
                            Model = "Ranchero",
                            Registered = new DateTime(2013, 2, 2, 16, 0, 10, 364, DateTimeKind.Unspecified).AddTicks(5518),
                            TopSpeed = 210,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = new Guid("1a1d848b-0130-6ce4-423d-012e9b06ee37"),
                            Color = 145,
                            Fuel = "Electric",
                            Manufacturer = "Chevrolet",
                            Model = "ATS",
                            Registered = new DateTime(2018, 4, 6, 22, 4, 31, 644, DateTimeKind.Unspecified).AddTicks(6978),
                            TopSpeed = 120,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = new Guid("bf090896-582b-0914-81b2-1c4d90ee1b7e"),
                            Color = 148,
                            Fuel = "Electric",
                            Manufacturer = "Land Rover",
                            Model = "Altima",
                            Registered = new DateTime(1991, 5, 22, 7, 24, 34, 473, DateTimeKind.Unspecified).AddTicks(4739),
                            TopSpeed = 180,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = new Guid("1e0f0cef-238d-454c-64f9-cc86122741b9"),
                            Color = 137,
                            Fuel = "Diesel",
                            Manufacturer = "Honda",
                            Model = "Model T",
                            Registered = new DateTime(1992, 5, 29, 2, 39, 43, 938, DateTimeKind.Unspecified).AddTicks(9682),
                            TopSpeed = 200,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = new Guid("d017495d-1de8-4709-ee84-9b1ab31b3986"),
                            Color = 129,
                            Fuel = "Diesel",
                            Manufacturer = "Land Rover",
                            Model = "XTS",
                            Registered = new DateTime(1997, 10, 9, 2, 14, 42, 549, DateTimeKind.Unspecified).AddTicks(423),
                            TopSpeed = 200,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("6b325708-1c3d-9195-f070-53b2d5765263"),
                            Color = 70,
                            Fuel = "Hybrid",
                            Manufacturer = "Toyota",
                            Model = "Fiesta",
                            Registered = new DateTime(2015, 10, 16, 15, 0, 11, 460, DateTimeKind.Unspecified).AddTicks(1521),
                            TopSpeed = 150,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = new Guid("a7d99d8e-4a4d-c60f-6398-e10e78b6b2cc"),
                            Color = 106,
                            Fuel = "Hybrid",
                            Manufacturer = "Audi",
                            Model = "A4",
                            Registered = new DateTime(2003, 8, 15, 5, 3, 12, 13, DateTimeKind.Unspecified).AddTicks(5851),
                            TopSpeed = 270,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = new Guid("d1931064-5d44-e6a2-6491-4aa3ce637548"),
                            Color = 105,
                            Fuel = "Electric",
                            Manufacturer = "Nissan",
                            Model = "1",
                            Registered = new DateTime(2020, 1, 5, 1, 29, 7, 32, DateTimeKind.Unspecified).AddTicks(9592),
                            TopSpeed = 220,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("8e75add9-8587-cc0f-622e-347596b979ca"),
                            Color = 28,
                            Fuel = "Diesel",
                            Manufacturer = "Mazda",
                            Model = "Impala",
                            Registered = new DateTime(2009, 2, 19, 6, 38, 51, 859, DateTimeKind.Unspecified).AddTicks(6221),
                            TopSpeed = 140,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("10b568e4-c9ac-6fff-4f70-a8ba24cfce1b"),
                            Color = 175,
                            Fuel = "Hybrid",
                            Manufacturer = "Smart",
                            Model = "A8",
                            Registered = new DateTime(1999, 11, 15, 14, 47, 14, 530, DateTimeKind.Unspecified).AddTicks(3888),
                            TopSpeed = 170,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = new Guid("16cd8fde-2f40-7667-eaab-9a9125d17462"),
                            Color = 163,
                            Fuel = "Diesel",
                            Manufacturer = "Mercedes Benz",
                            Model = "Focus",
                            Registered = new DateTime(1990, 11, 11, 18, 22, 53, 520, DateTimeKind.Unspecified).AddTicks(803),
                            TopSpeed = 180,
                            Type = "Extended Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("a59bfb55-2750-46b8-9d4a-7ad780dfb3bf"),
                            Color = 74,
                            Fuel = "Hybrid",
                            Manufacturer = "Audi",
                            Model = "Ranchero",
                            Registered = new DateTime(1999, 1, 22, 3, 22, 6, 495, DateTimeKind.Unspecified).AddTicks(6471),
                            TopSpeed = 180,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("f2ec4aa8-84c2-b5b5-e9f0-90771aa58917"),
                            Color = 162,
                            Fuel = "Gasoline",
                            Manufacturer = "Chevrolet",
                            Model = "El Camino",
                            Registered = new DateTime(2020, 9, 13, 3, 14, 10, 137, DateTimeKind.Unspecified).AddTicks(9410),
                            TopSpeed = 250,
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = new Guid("a34f83f4-fc7f-300a-f0cc-bef25b6334f6"),
                            Color = 75,
                            Fuel = "Hybrid",
                            Manufacturer = "Ferrari",
                            Model = "Colorado",
                            Registered = new DateTime(1992, 6, 20, 18, 38, 51, 457, DateTimeKind.Unspecified).AddTicks(9546),
                            TopSpeed = 210,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = new Guid("d0b61a99-8bab-8ba8-f5fe-50f86e73e136"),
                            Color = 60,
                            Fuel = "Hybrid",
                            Manufacturer = "Polestar",
                            Model = "Beetle",
                            Registered = new DateTime(2020, 12, 11, 23, 8, 49, 571, DateTimeKind.Unspecified).AddTicks(5512),
                            TopSpeed = 280,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = new Guid("3b1ab42d-16a4-1ab3-1303-1cb588c82b5f"),
                            Color = 150,
                            Fuel = "Hybrid",
                            Manufacturer = "Hyundai",
                            Model = "Aventador",
                            Registered = new DateTime(1999, 9, 27, 18, 48, 40, 304, DateTimeKind.Unspecified).AddTicks(6100),
                            TopSpeed = 110,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = new Guid("b0df83c5-b1da-5025-bb3c-67891b904f04"),
                            Color = 44,
                            Fuel = "Gasoline",
                            Manufacturer = "Lamborghini",
                            Model = "Fiesta",
                            Registered = new DateTime(1992, 11, 23, 0, 30, 11, 272, DateTimeKind.Unspecified).AddTicks(9364),
                            TopSpeed = 290,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("808e6e58-571c-936b-be21-4a55b8c465d9"),
                            Color = 174,
                            Fuel = "Gasoline",
                            Manufacturer = "Bugatti",
                            Model = "Wrangler",
                            Registered = new DateTime(2015, 6, 15, 7, 28, 5, 333, DateTimeKind.Unspecified).AddTicks(6459),
                            TopSpeed = 110,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("4354ce0f-86ca-cf10-7573-c686424c3009"),
                            Color = 111,
                            Fuel = "Hybrid",
                            Manufacturer = "Mercedes Benz",
                            Model = "Grand Cherokee",
                            Registered = new DateTime(1993, 10, 21, 18, 26, 23, 134, DateTimeKind.Unspecified).AddTicks(8356),
                            TopSpeed = 140,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = new Guid("680f3f97-4f7a-f041-4437-2f7eb2c714a0"),
                            Color = 79,
                            Fuel = "Hybrid",
                            Manufacturer = "Maserati",
                            Model = "Element",
                            Registered = new DateTime(2017, 2, 26, 1, 2, 10, 542, DateTimeKind.Unspecified).AddTicks(7121),
                            TopSpeed = 260,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = new Guid("e3388c23-12ba-78cf-d63e-93bd03ba1d95"),
                            Color = 30,
                            Fuel = "Diesel",
                            Manufacturer = "Volkswagen",
                            Model = "Jetta",
                            Registered = new DateTime(2017, 2, 5, 7, 32, 24, 588, DateTimeKind.Unspecified).AddTicks(9286),
                            TopSpeed = 280,
                            Type = "Wagon"
                        },
                        new
                        {
                            Id = new Guid("aee4427e-fa9c-fc15-59a4-01ecdc416b86"),
                            Color = 97,
                            Fuel = "Hybrid",
                            Manufacturer = "Fiat",
                            Model = "Alpine",
                            Registered = new DateTime(2014, 11, 14, 12, 37, 36, 685, DateTimeKind.Unspecified).AddTicks(650),
                            TopSpeed = 160,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = new Guid("19eee610-a1d2-705e-ee10-bebaa1d66332"),
                            Color = 145,
                            Fuel = "Diesel",
                            Manufacturer = "BMW",
                            Model = "Land Cruiser",
                            Registered = new DateTime(1992, 2, 22, 15, 12, 15, 647, DateTimeKind.Unspecified).AddTicks(512),
                            TopSpeed = 300,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = new Guid("ac145341-0da4-ba8f-8d5f-38d3c8aee043"),
                            Color = 77,
                            Fuel = "Hybrid",
                            Manufacturer = "Kia",
                            Model = "Grand Caravan",
                            Registered = new DateTime(1999, 4, 14, 4, 24, 15, 257, DateTimeKind.Unspecified).AddTicks(6408),
                            TopSpeed = 210,
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = new Guid("417ab0c9-9841-e4fe-f00e-18adc5bdf4ba"),
                            Color = 76,
                            Fuel = "Electric",
                            Manufacturer = "Dodge",
                            Model = "Mercielago",
                            Registered = new DateTime(2014, 3, 13, 17, 28, 22, 199, DateTimeKind.Unspecified).AddTicks(3796),
                            TopSpeed = 280,
                            Type = "Wagon"
                        });
                });

            modelBuilder.Entity("BusinessModel.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96ba173e-04ae-3bcd-9986-9e56f0adbf3a"),
                            Email = "Josefina.Barton@hotmail.com",
                            FirstName = "Josefina",
                            LastName = "Barton"
                        },
                        new
                        {
                            Id = new Guid("6ecc5d17-098b-5714-9ab0-36cfd6280bb3"),
                            Email = "Abel.Leuschke14@hotmail.com",
                            FirstName = "Abel",
                            LastName = "Leuschke"
                        },
                        new
                        {
                            Id = new Guid("090595dc-676e-e76b-f10d-46d827baed27"),
                            Email = "Llewellyn.Erdman@gmail.com",
                            FirstName = "Llewellyn",
                            LastName = "Erdman"
                        },
                        new
                        {
                            Id = new Guid("1a8767d6-b385-a886-af72-7663a7813769"),
                            Email = "Tate_Ward@yahoo.com",
                            FirstName = "Tate",
                            LastName = "Ward"
                        },
                        new
                        {
                            Id = new Guid("fd8929bf-5100-9fc6-e4e0-f50e71052d7e"),
                            Email = "Carroll77@yahoo.com",
                            FirstName = "Carroll",
                            LastName = "Brakus"
                        },
                        new
                        {
                            Id = new Guid("75cf9b42-3880-beb5-a060-0bf84a173efd"),
                            Email = "Alejandrin21@gmail.com",
                            FirstName = "Alejandrin",
                            LastName = "Erdman"
                        },
                        new
                        {
                            Id = new Guid("548191ca-7b35-ea0a-92b1-fa06747c8eb9"),
                            Email = "Rosamond_Goyette@yahoo.com",
                            FirstName = "Rosamond",
                            LastName = "Goyette"
                        },
                        new
                        {
                            Id = new Guid("15ea8044-ee27-80ee-d264-51253577094e"),
                            Email = "Laverne.Huel@hotmail.com",
                            FirstName = "Laverne",
                            LastName = "Huel"
                        },
                        new
                        {
                            Id = new Guid("f211ae0d-9ad5-44b0-9503-49af28861196"),
                            Email = "Vinnie_Toy@gmail.com",
                            FirstName = "Vinnie",
                            LastName = "Toy"
                        },
                        new
                        {
                            Id = new Guid("e0a84cc0-053f-6b84-6734-5a650c36d1d8"),
                            Email = "Arne_Johnston95@hotmail.com",
                            FirstName = "Arne",
                            LastName = "Johnston"
                        });
                });

            modelBuilder.Entity("BusinessModel.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OrderId");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CustomerId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BusinessModel.Models.Auto", b =>
                {
                    b.HasOne("BusinessModel.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("BusinessModel.Models.Order", b =>
                {
                    b.HasOne("BusinessModel.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BusinessModel.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
