@VehicleManagement_HostAddress = https://localhost:44300
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJSLiBSb290IiwiZW1haWwiOiJyb290QGV4YW1wbGUuY29tIiwianRpIjoiMmZlMjdhY2MtNGZjMi00MGViLTllYjAtZGE4MzYzNTdjYWQwIiwibmJmIjoxNzU0NDAyMzE3LCJleHAiOjE3NTQ0ODg3MTcsImlhdCI6MTc1NDQwMjMxNywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMzMiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo0NDMwMCJ9._bVKg1-NVgn-tEPkSivPZMeCohdPykPHxBhizmlpe-I

POST {{VehicleManagement_HostAddress}}/account/login
Content-Type: application/json
Accept: application/json

{
  "username": "R. Root",
  "password": "Syst3m"
}

###

POST {{VehicleManagement_HostAddress}}/account/register
Content-Type: application/json
Accept: application/json

{
  "username": "WebApiUser123",
  "email": "webapiuser123@example.com",
  "password": "Syst3m"
}

###

GET {{VehicleManagement_HostAddress}}/api/v1/vehicles/
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{VehicleManagement_HostAddress}}/api/v1/vehicles/
Accept: text/csv

###

GET {{VehicleManagement_HostAddress}}/api/v1/vehicles/098b6ecc-5714-b09a-36cf-d6280bb3c707
Accept: application/json

###

GET {{VehicleManagement_HostAddress}}/api/v1/vehicles/098b6ecc-5714-b09a-36cf-d6280bb3c707
Accept: application/xml

###

POST {{VehicleManagement_HostAddress}}/api/v1/vehicles
Content-Type: application/json
Accept: application/json

{
  "manufacturer": "Honda",
  "model": "Civic",
  "color": 42,
  "fuel": "Gasoline",
  "topSpeed": 200,
  "type": "Sedan",
  "registered": "2022-01-01T00:00:00Z"
}

###

POST {{VehicleManagement_HostAddress}}/api/v1/vehicles
Content-Type: application/json
Accept: application/json

{
  "manufacturer": "Dacia",
  "model": "Logan",
  "color": "red",
  "fuelType": "Gasoline",
  "topSpeed": 123,
  "type": "Sedan",
  "registered": "2022-01-01T00:00:00Z"
}

###

PUT {{VehicleManagement_HostAddress}}/api/v1/vehicles/098b6ecc-5714-b09a-36cf-d6280bb3c707
Content-Type: application/json
Authorization: Bearer {{token}}
Accept: application/json

{
  "manufacturer": "BMW",
  "model": "Isetta",
  "fuel": "Gasoline",
  "color": "Red",
  "type": "Coupe",
  "topSpeed": 50,
  "registered": "1950-01-01T00:00:00Z"
}

###

DELETE {{VehicleManagement_HostAddress}}/api/v1/vehicles/96ba173e-04ae-3bcd-9986-9e56f0adbf3a
Authorization: Bearer {{token}}
Accept: application/json

